@echo off
cls
color A
title One UI Optimizer for Windows 1.0 (tested on One UI 6 and 7)
cd /d "%~dp0"

:verify
if not exist adb.exe (
    echo adb.exe does not exist!
    pause
    exit /b
)
if not exist AdbWinApi.dll (
    echo AdbWinApi.dll does not exist!
    pause
    exit /b
)
if not exist AdbWinUsbApi.dll (
    echo AdbWinUsbApi.dll does not exist!
    pause
    exit /b
)
if not exist opti.bat (
    echo opti.bat does not exist!
    pause
    exit /b
)
if not exist debloatw.bat (
    echo debloatw.bat does not exist!
    pause
    exit /b
)
if not exist dfop.bat (
    echo dfop.bat does not exist!
    pause
    exit /b
)
if not exist anima.bat (
    echo anima.bat does not exist!
    pause
    exit /b
)
if exist name (
    type name
) else (
    echo name does not exist.
    exit /b
)

echo Requirements:
echo - Samsung device running One UI with USB debugging enabled
echo - A USB cable
echo - A PC running Windows 7 or later
echo - Samsung USB Drivers
echo - AOSP ADB/Fastboot Drivers
echo - A cup of coffee
echo - Patience

echo .
echo Warnings:
echo - Your device may reboot during the optimization
pause

:automatic_verification
cls
title Detecting device...
type name
echo Detecting device automatically...
for /f "tokens=1,2" %%a in ('adb devices ^| findstr /v "List"') do (
    if "%%b"=="device" goto :opt_choice
) else (
echo No device detected. Let's try manually...
timeout /t 2 >nul
goto :check_device
)

:check_device
cls
title Device check (manual)
type name
adb devices
echo Let's check if your device appears here:
pause

:device_response
cls
type name
set /p d=Did it appear? (Y/N): 
if /i "%d%"=="Y" (
    goto :opt_choice
) else if /i "%d%"=="N" (
    echo Please check USB cable and driver installation.
    pause
    goto :check_device
) else (
    echo Invalid answer, try again.
    timeout /t 2 >nul
    goto :device_response
)

:opt_choice
cls
title Device connected - Optimization in progress
type name
echo Device detected:
adb shell getprop ro.product.manufacturer
adb shell getprop ro.product.model
adb shell getprop ro.build.version.release
pause

set /p o=Do you want to remove Samsung bloatware? (Y/N): 
if /i "%o%"=="Y" (
    goto :remove_bloatware
) else if /i "%o%"=="N" (
    echo Skipping bloatware removal...
    timeout /t 1 >nul
    goto :dirty_flash_opt
) else (
    echo Invalid answer, try again.
    timeout /t 2 >nul
    goto :opt_choice
)

:remove_bloatware
cls
type name
echo Optimizing device settings...
call opti.bat
echo Settings applied.
timeout /t 1 >nul

echo Starting bloatware removal...
call debloatw.bat

echo Bloatware removed.
timeout /t 1 >nul

:dirty_flash_opt
cls
type name
echo Running dirty flash optimization... Do NOT unplug the device!
call dfop.bat
echo Optimization complete.
timeout /t 2 >nul

:manual_steps
cls
type name
echo I'll guide you through final manual optimization steps.
pause
cls
type name
echo Step 1: Unlock your device.
pause
cls
type name
echo Step 2: Disable auto-updates in Google Play Store.
pause
cls
type name
echo Step 3: Go to Settings > Device Care.
echo Enable auto restart and scheduled restart and set a time when you're not using the device (e.g., while sleeping).
pause
cls
type name
echo Step 4: Disable notification bubbles in Settings.
pause
cls
type name
echo Step 5: Disable location & sync icons in the status bar.
pause
cls
type name
echo Step 6: Go to Sounds and Vibrations and disable unnecessary sounds.
pause
cls
type name
echo Step 7: Turn off Bluetooth when not in use.
pause
cls
type name
echo Making animations smoother/faster...
call anima.bat
echo Animations adjusted.
timeout /t 1 >nul

echo Rebooting device...
adb reboot
pause

:restart_pc
cls
type name
set /p r=Do you want to restart the computer now? (Y/N): 
if /i "%r%"=="Y" (
    shutdown -r -f -t 0
) else if /i "%r%"=="N" (
    goto :goodbye
) else (
    echo Invalid answer, try again.
    timeout /t 1 >nul
    goto :restart_pc
)

:goodbye
cls
title One UI Optimizer By Filipe (Goodbye)
type end
echo One UI Optimization Tool by Filipe Daniel
echo © Filipe Daniel, 2025. All rights reserved 
echo Telegram: @filipe13
echo Ascii Art generated by patorjk.com
echo Made with GNOME Text Editor
echo Linux version soon...
echo Not made for commercial use
echo Version 1.3
pause
exit
